version: '3.8'

services:
  flickd-engine:
    build: .
    container_name: flickd-engine
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - model_cache:/root/.cache
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - flickd-network

  redis:
    image: redis:7-alpine
    container_name: flickd-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - flickd-network

  nginx:
    image: nginx:alpine
    container_name: flickd-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - flickd-engine
    restart: unless-stopped
    networks:
      - flickd-network

volumes:
  redis_data:
  model_cache:

networks:
  flickd-network:
    driver: bridge
